
footprint: [ [-0.8,-0.33], [0.8,-0.33], [0.8,0.33], [-0.8,0.33] ]
robot_base_frame: base_link

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 10.0
 raytrace_range: 3.5
 inflation_radius: 3
 track_unknown_space: true
 combination_method: 1
 min_obstacle_height: -1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: rbcar/laser/scan, marking: true, clearing: true, inf_is_valid: true}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     10  # max. distance from an obstacle at which costs are incurred for planning paths.


